### ISSUE TITLE
HA 2023.11.3 no longer works with v1.3.2

### ISSUE THREAD

**Issue by ping-localhost** [Sian-Lee-SA/Home-Assistant-Switch-Manager#186]
Due to changes for https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/issues/185, Switch Manager is now broken in HA 2023.11.3. 

```
Logger: homeassistant.setup
Source: setup.py:215
First occurred: 10:25:51 (1 occurrences)
Last logged: 10:25:51

Setup failed for custom integration switch_manager: Unable to import component: cannot import name 'format_schema_error' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 816, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/switch_manager/__init__.py", line 19, in <module>
    from homeassistant.config import format_schema_error
ImportError: cannot import name 'format_schema_error' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
```

**Comment by ping-localhost** [comment]
As a side-note, I do not run beta/.0 versions, as I do not have a staging machine and I rather not break my home :)

**Comment by ping-localhost** [comment]
Just read that the release note does mention only 2023.12+ is supported, so I'll close this issue 😅
