### ISSUE TITLE
Error after updating to 2023.12

### ISSUE THREAD

**Issue by Aaroneisele55** [Sian-Lee-SA/Home-Assistant-Switch-Manager#196]
Hello,
I have this error after updating to 2023.12:

`Logger: homeassistant.setup
Source: setup.py:251
First occurred: 06:13:45 (1 occurrences)
Last logged: 06:13:45

Setup failed for custom integration 'switch_manager': Unable to import component: cannot import name '_format_config_error' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/switch_manager/__init__.py", line 19, in <module>
    from homeassistant.config import _format_config_error
ImportError: cannot import name '_format_config_error' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
`

What can I do to resolve this?
It prevents all my Hue switches (via ZHA) from working.

Best regards 
Aaron Eisele
